<a href="https://colab.research.google.com/github/msft-jaiverma/AngularJS6-ADAL-GraphAPI/blob/master/FinalModel1_CreditRiskModel_(1)_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Loading the libraries
import numpy as np
# numpy stands for numerical python
import pandas as pd
# pandas stands for panel data
import matplotlib.pyplot as plt
# Matlab plot library

In [5]:
# read the data file
data = pd.read_csv("Churn_Modelling.csv")
# Check is the data is properly loaded
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
X = data.iloc[:,3:13].values
X
# Separate X and y
y = data.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0])

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:,2] = labelencoder.fit_transform(X[:,2]) # Gender
X[:,1] = labelencoder.fit_transform(X[:,1]) # Geography
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
# Get the library from sklearn.compose 
from sklearn.compose import ColumnTransformer
# OneHot Encoder has been applied to column 1
# I have given the ColumnTransformer function a name of my choice which is country
# The functionality has been passed onto the variable ct but still not applied on the data
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
# We shall now apply it on the data
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

Convert the data into a dataframe for each of understanding. Replace the countries with X1, X2 and X3 the values we have after one-hot encoding. The countries have been replaced by X1, X2 and X3 which is a vector.
Example: France is now 1,0,0
Spain has been replaced by 0,0,1

In [9]:
# Call the pandas dataframe command to convert the data into a frame which can be used further
# Note you are converting data type from Numpy array to Pandas
X = pd.DataFrame(X,columns = ["X1", "X2", "X3", "Credit Score", "Gender", "Age","Tenure", "Balance", "NumofProducts", "HasCrCard", "IsActive Member", "Estimated Salary"])
X

X1 X2 X3  ... HasCrCard IsActive Member Estimated Salary
0     1  0  0  ...         1               1           101349
1     0  0  1  ...         0               1           112543
2     1  0  0  ...         1               0           113932
3     1  0  0  ...         0               0          93826.6
4     0  0  1  ...         1               1          79084.1
...  .. .. ..  ...       ...             ...              ...
9995  1  0  0  ...         1               0          96270.6
9996  1  0  0  ...         1               1           101700
9997  1  0  0  ...         0               1          42085.6
9998  0  1  0  ...         1               0          92888.5
9999  1  0  0  ...         1               0          38190.8

[10000 rows x 12 columns]

In [ ]:
# From the datafram drop X1
# axis = 1 indicates where should Python look for the variable X1
# The answer is that it should look for X1 along the X-axis and hence axis is set to 1
# If looking along the Y-axis the axis should be set to 0
X = X.drop("X1", axis = 1)
X

In [10]:
#Split the dataset into train and test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

In [12]:
#Feature Scaling 

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

#Standarized the train data

X_train = sc.fit_transform(X_train)

#Transform the test data, we do not need to standarized it.

X_train = sc.transform(X_test)